#!/bin/bash

# This script is called by ~/.conf/labwc/autostart
# The sleep was originally included to allow enough time for the
# desktop background to be loaded before the program starts.
# It might not be needed any longer.

sleep 5
gio launch /home/pi/Desktop/pool_dashboard.desktop
